import os

NOTION_TOKEN = os.environ.get("NOTION_TOKEN")

UB_ROOT_BLOCK_ID = os.environ["UB_ROOT_BLOCK_ID"]

# Ultimate Brain Databases
UB_NOTES_DATABASE = os.environ["UB_NOTES_DATABASE"]
UB_MILESTONES_DATABASE = os.environ["UB_MILESTONES_DATABASE"]
UB_PROJECTS_DATABASE = os.environ["UB_PROJECTS_DATABASE"]
UB_TASKS_DATABASE = os.environ["UB_TASKS_DATABASE"]
UB_GOALS_DATABASE = os.environ["UB_GOALS_DATABASE"]
UB_AREAS_AND_RESOURCES_DATABASE = os.environ["UB_AREAS_AND_RESOURCES_DATABASE"]
